@BASE_URL = http://localhost:3000/api


// LOGIN
###
POST  {{BASE_URL}}/users/login
Content-Type: application/json

{
    "email": "1234@gmail.com",
    "password": "123456"
}

// REGISTER
###
POST  {{BASE_URL}}/users/register
Content-Type: application/json

{
    "email": "1234@gmail.com",
    "password": "123456",
    "repassword": "123456",
    "gender": "male",
    "username": "maden1234",
    "name" : "Mustafa",
    "surname": "Maden"
}

//Kullanıcı profil sayfası
###
GET  {{BASE_URL}}/users/myprofile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTA1MzZlMjdkNjA3YTRkNTgxOTZlNGQiLCJpYXQiOjE2Mjc3MzE4MzUsImV4cCI6MTYyNzc2NzgzNX0.17aiYwQmPOzLxVpvLi0_Fqq3QCuLt_kFr-AXhxuxBlo

{

}


//Kullanıcı profil sayfası güncelleme
###
PATCH   {{BASE_URL}}/users/myprofile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTA1MzZlMjdkNjA3YTRkNTgxOTZlNGQiLCJpYXQiOjE2Mjc3MzE4MzUsImV4cCI6MTYyNzc2NzgzNX0.17aiYwQmPOzLxVpvLi0_Fqq3QCuLt_kFr-AXhxuxBlo

{
    "chatChannel": "asd1@gmail.com"
}



























###
GET {{BASE_URL}}

###
GET  {{BASE_URL}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTA1MjhiZTIzZWUzZDNmOGNhZGUyODkiLCJpYXQiOjE2Mjc3MjgxMzYsImV4cCI6MTYyNzc2NDEzNn0.ABX71lObKqdUV7bo7K_hMzwI2hhXEttIqC6qbNoKstM


###
GET  {{BASE_URL}}/users/52


###
PATCH   {{BASE_URL}}/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGYxYTUzZjM5YmU4OTNkZjQyOWIxZDEiLCJpYXQiOjE2MjY0NDkyMjMsImV4cCI6MTYyNjQ1MjgyM30.ETl-uT8ujqThINgfNDhHIcA1c2g3C-Q-yztq8PK-_gU

{
    "isim": "maden2sd",
    "sifre": "123456"
}


###
PATCH   {{BASE_URL}}/users/60f1a53f39be893df429b1d1
Content-Type: application/json

{
    "isim": "maden22",
    "sifre": "123456"
}

###
DELETE  {{BASE_URL}}/users/60eae440623deb2e8c92f5fa
Content-Type: application/json


###
DELETE  {{BASE_URL}}/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGYxM2I4YmM5NjhhYzE2MjAzYmNiYjkiLCJpYXQiOjE2MjY0MjI1NjYsImV4cCI6MTYyNjQyNjE2Nn0.hNcdkNvUWYz3Fg0_SsmY9Keafkakm7UkNSFZOuWImak

###
GET  {{BASE_URL}}/users/deleteAll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGYxYTUzZjM5YmU4OTNkZjQyOWIxZDEiLCJpYXQiOjE2MjY0NDkyMjMsImV4cCI6MTYyNjQ1MjgyM30.ETl-uT8ujqThINgfNDhHIcA1c2g3C-Q-yztq8PK-_gU
